---
title: "betaDelta: Example Using the BetaDelta Function"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Pesigan-Sun-Cheung-2023
  @Yuan-Chan-2011
  @Jones-Waller-2015
  @NationalResearchCouncil-1982
vignette: >
  %\VignetteIndexEntry{betaDelta: Example Using the BetaDelta Function}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



In this example, a multiple regression model is fitted
using program quality ratings (`QUALITY`) as the regressand/outcome variable
and number of published articles attributed to the program faculty members (`NARTIC`),
percent of faculty members holding research grants (`PCTGRT`), and
percentage of program graduates who received support (`PCTSUPP`) as regressor/predictor variables
using a data set from 1982 ratings of 46 doctoral programs in psychology in the USA [@NationalResearchCouncil-1982].
Confidence intervals for the standardized regression coefficients are generated
using the `BetaDelta()` function from the `betaDelta` package following @Yuan-Chan-2011 and @Jones-Waller-2015.


``` r
library(betaDelta)
```




``` r
df <- betaDelta::nas1982
```

## Fit the regression model using the `lm()` function.


``` r
object <- lm(QUALITY ~ NARTIC + PCTGRT + PCTSUPP, data = df)
```

## Estimate the standardized regression slopes and the corresponding sampling covariance matrix.

#### Multivariate Normal-Theory Approach


``` r
BetaDelta(object, type = "mvn", alpha = 0.05)
```

#### Asymptotic Distribution-Free Approach


``` r
BetaDelta(object, type = "adf", alpha = 0.05)
```

## Methods


``` r
mvn <- BetaDelta(object, type = "mvn")
adf <- BetaDelta(object, type = "adf")
```

### summary

Summary of the results of `BetaDelta()`.


``` r
summary(mvn)
#>               est         se        t df            p        0.05%       0.5%
#> NARTIC  0.4951451 0.07585858 6.527213 42 6.924862e-08  0.226776787 0.29047366
#> PCTGRT  0.3914887 0.07702897 5.082357 42 8.144652e-06  0.118979841 0.18365947
#> PCTSUPP 0.2632477 0.07473457 3.522435 42 1.045529e-03 -0.001144198 0.06160887
#>              2.5%     97.5%     99.5%    99.95%
#> NARTIC  0.3420563 0.6482339 0.6998166 0.7635135
#> PCTGRT  0.2360380 0.5469395 0.5993180 0.6639976
#> PCTSUPP 0.1124272 0.4140682 0.4648865 0.5276396
#> attr(,"fit")
#> attr(,"print_summary")
#>            est     se      t df     p   0.05%   0.5%   2.5%  97.5%  99.5%
#> NARTIC  0.4951 0.0759 6.5272 42 0.000  0.2268 0.2905 0.3421 0.6482 0.6998
#> PCTGRT  0.3915 0.0770 5.0824 42 0.000  0.1190 0.1837 0.2360 0.5469 0.5993
#> PCTSUPP 0.2632 0.0747 3.5224 42 0.001 -0.0011 0.0616 0.1124 0.4141 0.4649
#>         99.95%
#> NARTIC  0.7635
#> PCTGRT  0.6640
#> PCTSUPP 0.5276
#> attr(,"digits")
#> [1] 4
#> attr(,"class")
#> [1] "summary.betadelta"
summary(adf)
#>               est         se        t df            p        0.05%       0.5%
#> NARTIC  0.4951451 0.06737560 7.349027 42 4.624211e-09  0.256787407 0.31336130
#> PCTGRT  0.3914887 0.07096857 5.516368 42 1.964333e-06  0.140419984 0.20001082
#> PCTSUPP 0.2632477 0.07690311 3.423109 42 1.392828e-03 -0.008815928 0.05575802
#>              2.5%     97.5%     99.5%    99.95%
#> NARTIC  0.3591757 0.6311146 0.6769290 0.7335029
#> PCTGRT  0.2482683 0.5347091 0.5829666 0.6425575
#> PCTSUPP 0.1080509 0.4184444 0.4707374 0.5353113
#> attr(,"fit")
#> attr(,"print_summary")
#>            est     se      t df      p   0.05%   0.5%   2.5%  97.5%  99.5%
#> NARTIC  0.4951 0.0674 7.3490 42 0.0000  0.2568 0.3134 0.3592 0.6311 0.6769
#> PCTGRT  0.3915 0.0710 5.5164 42 0.0000  0.1404 0.2000 0.2483 0.5347 0.5830
#> PCTSUPP 0.2632 0.0769 3.4231 42 0.0014 -0.0088 0.0558 0.1081 0.4184 0.4707
#>         99.95%
#> NARTIC  0.7335
#> PCTGRT  0.6426
#> PCTSUPP 0.5353
#> attr(,"digits")
#> [1] 4
#> attr(,"class")
#> [1] "summary.betadelta"
```

### coef

Calculate the standardized regression slopes.


``` r
coef(mvn)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4951451 0.3914887 0.2632477
coef(adf)
#>    NARTIC    PCTGRT   PCTSUPP 
#> 0.4951451 0.3914887 0.2632477
```

### vcov

Calculate the sampling covariance matrix of the standardized regression slopes.


``` r
vcov(mvn)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC   0.005754524 -0.003360334 -0.002166127
#> PCTGRT  -0.003360334  0.005933462 -0.001769723
#> PCTSUPP -0.002166127 -0.001769723  0.005585256
vcov(adf)
#>               NARTIC       PCTGRT      PCTSUPP
#> NARTIC   0.004539472 -0.002552698 -0.001742698
#> PCTGRT  -0.002552698  0.005036538 -0.001906216
#> PCTSUPP -0.001742698 -0.001906216  0.005914088
```

### confint

Generate confidence intervals for standardized regression slopes.


``` r
confint(mvn, level = 0.95)
#>             2.5 %    97.5 %
#> NARTIC  0.3420563 0.6482339
#> PCTGRT  0.2360380 0.5469395
#> PCTSUPP 0.1124272 0.4140682
confint(adf, level = 0.95)
#>             2.5 %    97.5 %
#> NARTIC  0.3591757 0.6311146
#> PCTGRT  0.2482683 0.5347091
#> PCTSUPP 0.1080509 0.4184444
```

## References
